matrix:
  primary:
    homeserverUrl: "https://t2bot.io"
    accessToken: "YourTokenHere"

discord:
  enabled: false
  botToken: "YourTokenHere"
  roomId: "!somewhere:example.org"
  channelId: "YourDiscordChannelId"

telegram:
  enabled: false
  botToken: "YourTokenHere"
  roomId: "!somewhere:example.org"
  channelId: -123456

irc:
  enabled: false
  host: "irc.libera.chat"
  port: 6697
  ssl: true
  nick: "t2pingbot"
  roomId: "!somewhere:example.org"
  channel: "#t2pingbot"

bots:
  enabled: false
  targets:
    - mxid: "@bot:example.org"
      command: "!bot help"
      # Regex to apply to returned `body`
      respRegex: "My Bot Help.*"
      # Can be shared with other bots (if their help commands don't overlap)
      roomId: "!somewhere:example.org"

monitoring:
  interval: 60000
  timeout: 30000
  port: 9000
