matrix:
  primary:
    homeserverUrl: "https://t2bot.io"
    accessToken: "YourTokenHere"

discord:
  enabled: false
  botToken: "YourTokenHere"
  roomId: "!somewhere:example.org"
  channelId: "YourDiscordChannelId"

telegram:
  enabled: false
  botToken: "YourTokenHere"
  roomId: "!somewhere:example.org"
  channelId: -123456

irc:
  enabled: false
  host: "irc.libera.chat"
  port: 6697
  ssl: true
  nickname: "t2pingbot"
  roomId: "!somewhere:example.org"
  channel: "#t2pingbot" 

monitoring:
  interval: 60000
  timeout: 30000
  port: 9000
